<div id="wrapper">
	<h1 id="nft-title">About The Bleep Machine</h1>
	<p id="nft-description">What if you could let the EVM sing?</p>
	<p id="nft-description">
		The Bleep Machine allows you to create algorithmic music using EVM bytecode. Its main
		inspiration are the bytebeats. The bytebeats (re)discovers the possibility of generating
		interesting musical sounds using simple mathematical formula. This was fascinating to discover
		the possibilities. You can found out more about this topic <a
			href="http://canonical.org/~kragen/bytebeat/">here</a
		>
	</p>
	<p>
		The Bleep Machine reimplements this system completely in solidity with the constraint of the
		ethereum virtual machine (see <a href="https://ethereum.github.io/yellowpaper/paper.pdf"
			>yellow paper</a
		>
		by Dr Gavin wood)
	</p>

	<p>
		This lets anyone submit bytecode to generate music. You can see a basic example of such bytecode <a
			href="../">here</a
		>. And since the whole wav file is generated by the contract it thus rely on zero infrastructure
		for listener, except the access to a browser with web3 access. Zero Ipfs. Zero backend.
	</p>
	<center>
		<a href="../">Play with it</a>
	</center>
</div>

<style>
	textarea {
		display: block;
		font-size: large;
	}

	* {
		background-color: #111111;
		color: wheat;
		margin: 0;
		padding: 0;
		font-family: Hack, monospace;
	}
	p,
	h1 {
		margin: 1em 1em 1em 1em;
	}
	:root {
		--width: 80vw;
	}

	button {
		font-size: 1em;
		border: 0.1em solid;
		padding: 0.3em;
		cursor: pointer;
	}
	#wrapper {
		text-align: center;
		height: 100%;
		margin: 0;
	}

	#nft-title {
		margin-top: 1em;
	}

	#nft-description {
		margin-bottom: 2em;
	}
</style>
